language: java

jdk:
  - openjdk8

env:
  - PROFILE=community
  - PROFILE=product

install: 
  - echo "travis_fold:start:install folding starts"
  - mvn clean install -s maven-settings.xml -DskipTests -B -q -D$PROFILE
  - echo "travis_fold:end:install folding ends"

script:
  - mvn -s maven-settings.xml test -f tests/pom.xml -D$PROFILE -B -fae
